### ISSUE TITLE
add empty check to avoid updating AFAS with empty values

### ISSUE THREAD

**Issue by arnoutvandervorst** [Tools4everBV/HelloID-Conn-Prov-Target-AFAS-Profit-Employees#1]
if ([String]::IsNullOrEmpty($emailaddress) -or [String]::IsNullOrEmpty($userPrincipalName)  ) {
    $auditMessage = "AD Emailaddress or UPN empty, skipping update..."
    $success = $False;
    $account = [PSCustomObject]@{
        'ref' = $p.ExternalId
    }

    #build up result
    $result = [PSCustomObject]@{
        Success= $success;
        AccountReference= $aRef;
        AuditDetails=$auditMessage;
        Account= $account;  
    };

    Write-Verbose $auditMessage -Verbose
        
    Write-Output $result | ConvertTo-Json -Depth 10;
    exit
}

**Comment by rschouten97** [comment]
This has been solved with the v2 version.
