### ISSUE TITLE
Todo: Create an instruction how to set custom fields (with a link to the forum post)

### ISSUE THREAD

**Issue by Rick-Jongbloed** [Tools4everBV/HelloID-Conn-Prov-Target-AFAS-Profit-Employees#11]
Todo: Create an instruction how to set custom fields (with a link to the forum post)

**Comment by rhouthuijzen** [comment]
@Rick-Jongbloed  forum post already exists. Will add an example in the readme and update the post with a link to our connector.

https://forum.helloid.com/forum/helloid-provisioning/1261-updating-a-custom-field-for-afas-employee
