### ISSUE TITLE
Type in scripting (madatory must be mandatory)

### ISSUE THREAD

**Issue by Rick-Jongbloed** [Tools4everBV/HelloID-Conn-Prov-Target-AFAS-Profit-Employees#14]
![image](https://github.com/Tools4everBV/HelloID-Conn-Prov-Target-AFAS-Profit-Employees/assets/3989834/3c634735-d175-40d1-bfb1-41e4b7fd7ea8)

**Comment by JeroenBL** [comment]
Solved.
