### ISSUE TITLE
Do not update emailPortal when the new email portal address equals the current email portal address

### ISSUE THREAD

**Issue by Rick-Jongbloed** [Tools4everBV/HelloID-Conn-Prov-Target-AFAS-Profit-Employees#2]
Just a quick note, will resolve this myself:

We have to make sure we add a check on the previous value of emailportal vs the current UPN, otherwise the connector will fail with the following message:

 17:07:49.77 06/09/2021 15:07:49 [Error] {"errorNumber":-2147180996,"externalMessage":"Het opgegeven e-mailadres is al in gebruik.\u000d\u000a\u000d\u000aKies een ander e-mailadres en probeer opnieuw.","profitLogReference":"46B212E24BDABB13D841D1A8845E8137"}

**Comment by rschouten97** [comment]
This has been solved with the v2 version.
